calista:
  pages:

    ucms_tree.list_all:
      datasource: ucms_tree.admin.datasource
      input:
        pager_enable: false
      view:
        show_filters: true
        show_pager: false
        templates:
          default: module:ucms_tree:Page/page-tree-admin.html.twig
        view_type: twig_page
