# Default node admin pages
calista:
  pages:

    # Carte page
    ucms_cart:
      id: ucms_cart
      datasource: ucms_contrib.datasource.cart
      input:
        limit_default: 16
        pager_enable: false
        search_enable: true
        search_param: cs
        sort_default_field: h.timestamp
        sort_default_order: desc
      view:
        enabled_filters: {}
        show_filters: false
        show_search: true
        show_sort: true
        templates:
          cart: module:ucms_contrib:views/Page/page-cart.html.twig
        view_type: twig_page

    # Content administration page
    ucms_contrib.content_admin.content:
      datasource: ucms_contrib.datasource.node
      input:
        limit_default: 24
        pager_enable: true
        pager_param: page
        search_enable: true
        search_param: s
        sort_default_field: n.changed
      view:
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          table: '@calista/Page/page.html.twig'
          grid: '@calista/Page/page-grid.html.twig'
        view_type: twig_page

    # Media administration page
    ucms_contrib.content_admin.media:
      datasource: ucms_contrib.datasource.node
      input:
        limit_default: 24
        pager_enable: true
        pager_param: page
        search_enable: true
        search_param: s
        sort_default_field: n.changed
      view:
        default_display: grid
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          table: '@calista/Page/page.html.twig'
          grid: '@calista/Page/page-grid.html.twig'
        view_type: twig_page
