calista:
  pages:

    # Cart view, derivative are generated at runtime using the input options
    # override when page is loaded and displayed
    ucms_cart:
      id: ucms_cart
      datasource: ucms_contrib.datasource.cart
      input:
        base_query: {}
        limit_default: 16
        pager_enable: false
        search_enable: true
        search_param: cs
        sort_default_field: h.timestamp
        sort_default_order: desc
      view:
        enabled_filters: {}
        show_filters: false
        show_search: true
        show_sort: true
        templates:
          cart: module:ucms_contrib:views/Page/page-cart.html.twig
        view_type: twig_page
